# Generated by Django 4.0.4 on 2022-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_header',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
