# Generated by Django 4.0.4 on 2022-07-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0004_delete_blog_bill_header_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_header',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill_lines',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
